channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=20.0.2
- pip:
  - mlflow==2.10.0
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - lightgbm==4.3.0
  - matplotlib==3.7.4
  - numpy==1.24.4
  - packaging==23.2
  - pandas==2.0.3
  - psutil==5.9.8
  - pyarrow==15.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
