apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-water-potability-backend-deploy
  # do not use _, instead use -
spec:
  replicas: 3

  # all pods with app="ml-water-potability-backend-deploy" belong to this deployment
  selector:
    matchLabels:
      app: ml-water-potability-backend-deploy

  # each pod gets label app="ml-water-potability-backend-deploy"
  template:
    metadata:
      labels:
        app: ml-water-potability-backend-deploy
    
    spec:
      containers:
      - name: ml-water-potability-backend-pod
        image: ml-water-potability-backend:latest
        imagePullPolicy: Never
        # set image pull policy to never whenever use image:latest
        # otherwise, by default it tries to pull image from docker.io
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
